### ISSUE TITLE
Feature Request: suppress all output

### ISSUE THREAD

**Issue by addisonklinke** [adrianlopezroche/fdupes#118]
I am looking to entirely suppress output to the console. Based on the documentation, I thought combining flags `-dNq` would achieve this, but information about retained and deleted files (the [+/-] syntax) is still printed to stdout. Is there a way to avoid this?

**Comment by GTP95** [comment]
Try to redirect the output to /dev/null. To do this write the command as usual and at the end append " > /dev/null". For example you could write something like this:
`$ fdupes -r ./ > /dev/null`
