### ISSUE TITLE
Feature Request : Ignore files by size

### ISSUE THREAD

**Issue by interstar** [adrianlopezroche/fdupes#119]
I love fdupes. 

Very useful. Thank you.

But I'm forever printing the results, sorting them with another script to find the biggest files so I can delete those.

Today we have so many, say Javascript projects with 100 copies of standard libraries. I don't want to remove these dupes. But I do want to know when I have three copies of the same large video file in completely different places on my drive.

So what would be really useful is a feature to ignore files (both comparison and for deleting) below a certain size. Eg. `fdupes --min-size 100000` to ignore any files less than 100000 bytes.

**Comment by thevikas** [comment]
+1

**Comment by alexandr7035** [comment]
+1

**Comment by adrianlopezroche** [comment]
Fixed in fda883c44de67b94bda697690407845b9db99f15.

**Comment by valentijnscholten** [comment]
See #128

**Comment by interstar** [comment]
Wow! How did I only see this today? Many months later.

Thank you, it's awesome you've done this.
