### ISSUE TITLE
--minsize not working when recursing into directories

### ISSUE THREAD

**Issue by valentijnscholten** [adrianlopezroche/fdupes#128]
The --minsize and --maxsize are very useful and the primary reason for me to build my own binary with these unreleased features.

However they don't work when recursing into (sub)directories.

On my filesystem directories are 4096 bytes, so any value for minsize above that will skip the directory, basically skipping everything.

example commands:
./fdupes -r /hd6/backup --minsize=4097
./fdupes -R /hd6/backup --minsize=4097

will skip all directories inside /hd6/backup because they are only 4096 bytes.

I am not a C(++) programmer so can't easily provide a reliable PR, but at first thought the size check should not be performed for directories I think?

**Comment by adrianlopezroche** [comment]
You're right, directory sizes should be ignored completely. Thanks for the
bug report.

**Comment by valentijnscholten** [comment]
As a programmer I couldn't help myself and try to make it work :)

See https://github.com/adrianlopezroche/fdupes/pull/129.

The size check should maybe also be skipped for symlinks, I don't know.

**Comment by adrianlopezroche** [comment]
For symlinks I think it should use the size of the file it points to.

**Comment by adrianlopezroche** [comment]
Fixed by 7ad4c5c476383163b45533c622d0e54a8146bc6b.
