### ISSUE TITLE
"fdupes: could not chdir to /home/[user]/[folder]

### ISSUE THREAD

**Issue by jmvp** [adrianlopezroche/fdupes#131]
"fdupes: could not chdir to /home/[user]/[folder]"
The above error message shows up when I try and run:
 
> fdupes /home/[my]/[folder]

And I can't figure it out. I see the line in your code which causes this error message to pop up, but lack the technical ability to suss out what I should do from there. I'm running Linux Mint 18.3.

Hoping someone will advise me here.

**Comment by adrianlopezroche** [comment]
It's probably a permissions issue. Try running "cd /home/[user]/[folder]"
and see what happens. You probably need to change permissions on that
folder or run as a user that has permission to access it.

**Comment by jmvp** [comment]
I should have clarified: I am the only user on the machine. I get the same result whether or not I preface the command with 'sudo'. Also, I have just confirmed, I get the same result when I run the command as root. There are no other commands on my machine that do this.

**Comment by adrianlopezroche** [comment]
If it's not a permissions issue then I have no idea what's going on. Just
in case, try the following command:

namei -l /path/to/file/giving/you/problems

and look at the permissions for each part to spot any issues with
permission bits.

**Comment by adrianlopezroche** [comment]
If it's not a permissions issue then I have no idea what's going on. Just
in case, try the following command:

namei -l /path/to/folder/giving/you/problems

and look at the permissions for each part to spot any issues with
permission bits.

**Comment by YannisCS50** [comment]
> "fdupes: could not chdir to /home/[user]/[folder]"
> The above error message shows up when I try and run:
> 
> > fdupes /home/[my]/[folder]
> 
> And I can't figure it out. I see the line in your code which causes this error message to pop up, but lack the technical ability to suss out what I should do from there. I'm running Linux Mint 18.3.
> 
> Hoping someone will advise me here.

Hi, I had the same problem on MacOS Catalina. I don't know if this works for you but give it a try.
I typed directly in the prompt "fdupes -r Documents" , without " " and without / before Documents.
Earlier I tried "fdupes -r /Documents" and I was receiving the same error message as you.
