### ISSUE TITLE
Accept a for all

### ISSUE THREAD

**Issue by PanderMusubi** [adrianlopezroche/fdupes#133]
Please, accept `a` for `all` as that is much less typing. Perhaps an extra option is needed in order to activate this feature.

Reported against version 1.6.1

**Comment by adrianlopezroche** [comment]
Already fixed in 2.0.0. ac468d96fdede845f9c20750b1fa19944807005f

**Comment by PanderMusubi** [comment]
Thanks, if you haven't done yet, perhaps notify the Debian package maintainer to upgrade. According to https://packages.debian.org/sid/fdupes they are still on version 1.6.1. Hence, Ubuntu is also still there https://launchpad.net/ubuntu/+source/fdupes

**Comment by sandrotosi** [comment]
I (Debian maintainer) am aware, just low in the priority list.
