### ISSUE TITLE
Specify max and mix size unit

### ISSUE THREAD

**Issue by jshdcmpbll** [adrianlopezroche/fdupes#134]
There is no mention in the README for what unit size must be specified for max an min file size.

Here is the C line that checks file size: https://github.com/adrianlopezroche/fdupes/blob/791fc12a093b77e8e897241bff731d6ec1e8f5b9/fdupes.c#L132

And here is a link that specifies the unit that the st_size function returns: https://linux.die.net/man/2/stat

**Comment by adrianlopezroche** [comment]
Fixed by ed3a17da4be91793e94e9b9053682110b2afa355.
