### ISSUE TITLE
fdupes 2.1.2 is stuck doesn't delete and only exit works

### ISSUE THREAD

**Issue by albertux** [adrianlopezroche/fdupes#153]
`mkdir tmp && cd tmp; touch x y`

fdupes version 2.1.2 in Debian bullseye, always is showing the down menu ( Preserve Files [1 - 2], all, help) :

I tried tab or enter or arrow keys but is just stuck only way to exit fdupes is type exit and do not delete duplicates

![Screenshot_2021-04-16_19-46-27](https://user-images.githubusercontent.com/9578/115099782-fbdd8000-9eec-11eb-8fed-5af71f5a9640.png)

**Comment by adrianlopezroche** [comment]
Try typing prune instead of hitting delete. Some distributions seem to have
the delete key disabled under ncurses for some reason.

**Comment by albertux** [comment]
Thank you that solve my problem

**Comment by choklo** [comment]
i had this issue and solved it as indicated here

"Try typing prune instead of hitting delete. Some distributions seem to have
the delete key disabled under ncurses for some reason."

upgrade von ubuntu fossal (x11) to jammy (wayland) produced this issue
