### ISSUE TITLE
Is there any way to match based on the first x MB of the file?

### ISSUE THREAD

**Issue by salamanders** [adrianlopezroche/fdupes#154]
I saw in the features that it does a MD5 of the start of the file, then continues on to the full comparison.  Is there any way to see the files that passed that first filter?

The reason I ask: I was copying some large files, but the copy got killed half way, so I may have some files where only the first half of the file is in the destination.  Comparing the first MB of every file would find the interrupted files.

**Comment by adrianlopezroche** [comment]
There's no way to do this without modifying the program.
