### ISSUE TITLE
Use the interactive mode on a output of fdupes (without -d)

### ISSUE THREAD

**Issue by kidburglar** [adrianlopezroche/fdupes#155]
Hello, sorry it's not very clear in the title, but I will try to explain it better here.

I sometimes use fdupes on big HDD, and it takes times to do the scan and delete interactively the duplicates files.
I thought it could be useful to use the normal command `fdupes -r ./hdd/ > output.txt` and maybe later having a way to parse my output.txt and delete the files interactively.

I can do something in bash maybe, but I think it could be useful in fdupes directly.

Have a good day.

**Comment by adrianlopezroche** [comment]
With ab5ef95e2b2633d0ca1a5ae0b8ac41abde160100 it should be possible to run `fdupes -r ./hdd/` with the -c option and subsequently re-run fdupes in interactive mode to perform the actual deletion. It should be much faster the second time around.
