### ISSUE TITLE
For every directories given, find duplicates in each subdirectory

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [adrianlopezroche/fdupes#157]
basically, as the title says. equivalent to `-R` then manually enter each subdirectory.

**Comment by Friday13th87** [comment]
i might not understand your question correctly. What i am understanding ist thet for example for:
main/sub1
main/sub2
main/sub3
main/sub4
you like to find duplicates only in sub1/sub2/sub3/sub4 but not between those subdirectories?
if so you can just run it like 
`for i in sub1 sub2 sub3 sub4; do fdupes -r main/$i; done`

if i got you wrong, you maybe should add some informations to your exact issue

**Comment by SodaWithoutSparkles** [comment]
Thats what I was thinking for. Using a for loop to do it is kinda janky, and I feel like this software should have the ability to do so. But this does the trick.

Although I have since moved to another de-dupe solution since I first post this issue.

If there are no objections within the next 24 hours, I would close this issue.

**Comment by aioue** [comment]
@SodaWithoutSparkles what solution for this did you use instead please?

**Comment by SodaWithoutSparkles** [comment]
I think it's `rdfind`. Can't remember what have I done back then
