### ISSUE TITLE
Unable to use backspace key in interactive mode

### ISSUE THREAD

**Issue by jamespole** [adrianlopezroche/fdupes#159]
I run Arch Linux using the [fdupes](https://archlinux.org/packages/community/x86_64/fdupes/) package which seems to be most current upstream version.

    james@james-laptop:~$ pacman -Q fdupes
    fdupes 1:2.1.2-1

    james@james-laptop:~$ uname -smr
    Linux 5.13.13-arch1-1 x86_64

For some reason I can't use the backspace key when in interactive mode. It just won't backspace at all, so when I make a mistake I have to Ctrl-C to retype my command. I observe this behavior on both my laptop as well as a VPS of mine running the same package/OS/Kernel.

Is this expected behavior or something I can help debug?

**Comment by adrianlopezroche** [comment]
Backspace, delete, and arrow keys should all work and work fine on my
system. Don't know what's going on with Arch, but maybe something to do
with ncurses or terminal keyboard maps?

**Comment by jamespole** [comment]
Interesting, I've just tested the arrow keys as well the delete key-and they all work fine! Seems to be just the backspace key that the culprit. After some research, I have changed my gnome-terminal configuration so it generates Control-H instead of an ASCII DEL for the Backspace key which seems to fix this problem.
