### ISSUE TITLE
fdupes gets stuck

### ISSUE THREAD

**Issue by forReason** [adrianlopezroche/fdupes#166]
I have tried fduoes on 2 data storage machines. for one machine it gets stuck at 80%, for one it gets stuck at 60%:
```
sudo fdupes -r /mnt -m
Progress [1396/2304] 60%
```

**Comment by leogitpub** [comment]
@forReason  I observed this same behaviour. Did you find any solution to this? Is this fixed?

**Comment by forReason** [comment]
nope. I use a different library now.

**Comment by forReason** [comment]
@leogitpub, seems reproducible to me the same way. 
I am trying to dedupe some 200TB of 100GB files. there is no chance to skip large files as they are all in the range of 95-105GB each.

**Comment by leogitpub** [comment]
Hmm, bummer. It would have been great if fdupes had something like --partial-hash just to find duplicates based on the first few bytes. Jdupes seems to give this feature.

@adrianlopezroche Hi, any plan on adding a --partial-hash feature?

**Comment by jbruchon** [comment]
@leogitpub Partial hash only matching is extremely dangerous. Don't do it unless you like losing your data.

**Comment by adrianlopezroche** [comment]
> Hi, any plan on adding a --partial-hash feature?

I have no intention of adding such a feature, but I do think I should be updating the overall progress indicator not just between files but also as files are read (e.g. as a percentage of total bytes processed).

**Comment by forReason** [comment]
it it a possibility to add compare files by name only? 
There is no way, I can scan my whole files with fdupes and there is no reason behind it (for me). 
My Library slowly but steadily approaches 1PB. My archive files are named in a predictable and unique manner ("Archive-2022-06-27-3:27:22PM").
The danger of  file duplicates arises when I add further disks and need to copy around data in order to optimize disk-space.

**Comment by adrianlopezroche** [comment]
@forReason, a filename-only comparison is beyond the scope of what fdupes is designed to do.

**Comment by forReason** [comment]
closing this issue, as fdupes is not the correct usecase for my application

**Comment by hashimaziz1** [comment]
> > Hi, any plan on adding a --partial-hash feature?
> 
> I have no intention of adding such a feature, but I do think I should be updating the overall progress indicator not just between files but also as files are read (e.g. as a percentage of total bytes processed).

Hi, is there any plan to revisit this?

**Comment by omkarium** [comment]
> closing this issue, as fdupes is not the correct usecase for my application

@hashimaziz1 @forReason btw, if you are interested to use a partial hash feature which I requested in the beginning — I have introduced it in my own project clonehunter. The readme explain it well. https://github.com/omkarium/clonehunter. Please check it out. However, it is a dangerous operation as Jbruchon mentioned. Test it thoroughly.
