### ISSUE TITLE
scans but does nothing else

### ISSUE THREAD

**Issue by UnknownSuperficialNight** [adrianlopezroche/fdupes#167]
command was: fdupes -rdN /home/artixn1ght/sourceprograms
ive tried : fdupes -r -d -N /home/artixn1ght/sourceprograms
sudo fdupes -rdN /home/artixn1ght/sourceprograms

still nothing working all it does it build block list then goes through all the files and stops no delete or anything else

**Comment by adrianlopezroche** [comment]
Do you know for a fact that there a duplicates in that directory?

**Comment by adrianlopezroche** [comment]
Unable to reproduce.
