### ISSUE TITLE
fdupes should ignore the .git folder, it makes no sense to delete file from repository clones

### ISSUE THREAD

**Issue by ricardosierra** [adrianlopezroche/fdupes#168]
I ran the command "fdupes -r -d -i -o time --reverse --noprompt ./" and it ended up removing files in the .git folder. can i revert? Wasn't the program to ignore the git folder? That doesn't make any sense!

**Comment by adrianlopezroche** [comment]
I really should add an --exclude option, but hardcoding the exclusion of .git directories is out of the question. There's an option to exclude hidden files and folders such as .git in fdupes already (-A --nohidden), but without it fdupes will treat .git directories just like any other. Unfortunately, there is no way to revert.
