### ISSUE TITLE
Replace duplicate files with hard links option is missing.

### ISSUE THREAD

**Issue by david-r-cox** [adrianlopezroche/fdupes#17]
Where did it go? See [this](https://launchpad.net/ubuntu/+source/fdupes/1.50-PR2-3) post for proof that it existed.

```
* debian/patches/50_bts284274_hardlinkreplace.dpatch
    - added -L / --linkhard to make fdupes replace files with hardlinks. Also
      update the manual page; thanks to Rupert Levene for the report and to
      Javier Fernández-Sanguino Peña for the patch; Closes: #284274
```

**Comment by jbruchon** [comment]
It seems to not have made it into the mainline code. FYI simonsj ported it into a fork of my personal fork of fdupes: https://github.com/simonsj/fdupes-jody/commit/83ddb432a478f94c893a48e2bb570be9736d4102
And upon seeing your report (and simonsj's own changes) I ported a modified version of the hardlink patch you linked to into my copy: https://github.com/jbruchon/fdupes-jody/commit/273e6547a97cb539766be6b35add2128c7c1b4b1
