### ISSUE TITLE
[feature request] Alternative handlling options to deleting duplicates

### ISSUE THREAD

**Issue by fmneto** [adrianlopezroche/fdupes#172]
Sometimes there is a need for duplicate files to be moved away instead of deleting. Either as an extra measure against data loss or some other reason. So, instead of just deleting duplicates, this feature would create a new directory and move duplicates into it.

Alternatively, duplicate files would be replaced by hard or symbolic links.

**Comment by adrianlopezroche** [comment]
I'm considering adding the linking feature, but I don't see moving files to another folder as being a feature I'd wish to add.
