### ISSUE TITLE
Published article on this great tool

### ISSUE THREAD

**Issue by StewAlexander-com** [adrianlopezroche/fdupes#179]
@adrianlopezroche, thanks for your work on this

In order to gain it some exposure wrote [this article](https://medium.com/awesome-command-line-tools-for-the-mac/introducing-fdupes-quickly-find-and-delete-duplicate-files-on-a-mac-for-free-cb509a030c45) about how to use it on an Apple Mac

 Thanks for making it!

**Comment by adrianlopezroche** [comment]
It's been a while since I last checked the issues list. Thank you for the article!
