### ISSUE TITLE
pre-compiled binary for Windows

### ISSUE THREAD

**Issue by scratcher28** [adrianlopezroche/fdupes#18]
Hi.
May you release a pre-compiled binary for Windows if possible, please?
Thanks in advice.

**Comment by jbruchon** [comment]
fdupes is not written to be compatible with Windows; however, my fork of fdupes is modified to compile with MinGW and you can find a pre-compiled binary of it here: https://github.com/jbruchon/fdupes-jody/releases/tag/v1.51-jody2
