### ISSUE TITLE
New release?🤔

### ISSUE THREAD

**Issue by kloczek** [adrianlopezroche/fdupes#180]
Looking on https://github.com/adrianlopezroche/fdupes/compare/v2.2.1...master I think that it would be geed to flush all already committed changes as new release.
Do you have any plans to to do that soon? 🤔

**Comment by adrianlopezroche** [comment]
I probably should. I was waiting to maybe add some more features such as a way to exclude files, but I could always leave that for a future release.

**Comment by adrianlopezroche** [comment]
Released as fdupes 2.3.0.
