### ISSUE TITLE
I'm unclear why i need to type exit if there are no more matches.. shouldn't it just exit?

### ISSUE THREAD

**Issue by haydonryan** [adrianlopezroche/fdupes#181]
First off - thankyou for this tool - it's a real lifesaver - and helps me organize lots of screenshots / pictures.  

I'm just wondering why i need to type 'exit' once it's done finding all matches (and i've deleted them) to me it should just show the command prompt on the next line.

**Comment by adrianlopezroche** [comment]
Because of the status bar that says how many files were deleted and how much space was reclaimed (people may want to look at it before exiting), and because one of my planned interactive features was/is adding an on-screen log of files deleted or preserved.

**Comment by haydonryan** [comment]
I understand - I feel like both of these would be good to spit out to the console screen after you leave the interactive session so that you could scroll up and see these stats, and things I deleted in the session.

You could always feature flag it behind a command line option eg --fast-exit
