### ISSUE TITLE
Is there a Windows binary?

### ISSUE THREAD

**Issue by gaiking-uk** [adrianlopezroche/fdupes#187]
This app looks really intriguing and useful, however I am a Windows user.

Is it possible to release a Windows executable / binary file please? (e.g. `FUDPES.exe`)

Thanks!

**Comment by adrianlopezroche** [comment]
I don't distribute any binaries, preferring to leave that to others. As fdupes is not designed with Windows in mind, compiling it to run on Windows could prove difficult. The Cygwin project has a fairly [old version](https://www.cygwin.com/packages/summary/fdupes.html) of fdupes available, but I haven't tried it myself.
