### ISSUE TITLE
fdupes - very slow on huge file types

### ISSUE THREAD

**Issue by mr-gosh** [adrianlopezroche/fdupes#2]
When searching for duplicates on very large file sizes the hashing algorithm is too slow.
There should be a command line option to use only file size and date for comparing.

Or at least an faster hashing algorithm?

On my Core i7 with 8GB Ram it takes several (10 - 50) seconds per file if they are several Gb large.

**Comment by ivan-dives** [comment]
https://github.com/adrianlopezroche/fdupes/pull/11 we are discussing patches that address the speed optimization

**Comment by adrianlopezroche** [comment]
I don't think multithreading is going to help. The problem is I/O, not CPU

**Comment by adrianlopezroche** [comment]
BTW,  I was wrong about dupes not doing partial hashing. The feature added
at some point and I had forgotten about it.
