### ISSUE TITLE
folder naming in released tarball is odd

### ISSUE THREAD

**Issue by yazug** [adrianlopezroche/fdupes#24]
tarball for 1.51 release is named fdupes-1.51.tar.gz

https://github.com/adrianlopezroche/fdupes/archive/fdupes-1.51.tar.gz

but when extracted it puts the files into fdupes-fdupes-1.51 folder instead of the expected fdupes-1.51

I would expect for a release tarball to extract to fdupes-1.51 instead.

**Comment by jbruchon** [comment]
This is because Github automatically generates the source tarball and the tag is assumed to be the version. The tag contains the name of the program which is why it's so strange.

**Comment by yazug** [comment]
That makes sense, for the next tag will it be just the version number or will it continue with the same naming for that tag? also with a cve for permissions fix and a few other enhancements are there any plans for a new tag of fdupes in the near future?

**Comment by jbruchon** [comment]
I don't know. I don't maintain the original fdupes; I have a fork at https://github.com/jbruchon/fdupes-jody that I actively develop. It uses tags in the format that Github tends to behave nicely with. From what I have seen, this code base is very conservatively managed, so I wouldn't expect any significant modifications on a short-term timescale. That was the primary motivation for making my own renamed fork (I develop very aggressively and don't want to wait.)

**Comment by adrianlopezroche** [comment]
I've changed the way I tag releases to avoid redundant directory names.
