### ISSUE TITLE
Option --order in 1.51

### ISSUE THREAD

**Issue by gerritgriebel** [adrianlopezroche/fdupes#37]
My intent was to keep the first file in alphabetic order of any duplicates. So I installed fdupes using macports and got

    $ /opt/local/bin/fdupes --version
    fdupes 1.51

I found no option for sorting, neither in man page nor in --help output. So I checked back here and found an --order option in source code. So I downloaded sources, build and used "--order name" option successfully.

Two issues:

- In --help you find as valid values "time" and "filename". In fact it's "time" and "name".
- The version downloaded, compiled and installed by macports is from http://nue.de.distfiles.macports.org/macports/distfiles/fdupes/1.51_1/fdupes-1.51.tar.gz and has the same output for --version as current head revision, but it's lacking --order option. No idea whose fault it is.

**Comment by jbruchon** [comment]
The sorting algorithm doesn't work right anyway; the sort is performed on matched pairs when the pairs arrive, but it should be performed on full chains of pairs once all duplicate finding work is finished. As it stands now, if pairs (1,5) (1,2) (2,3) (3,4) arrive, the pairs themselves will be ordered properly but the combined set (1,2,3,4,5) will have errors based on when each pair hits the sorting algorithm and could become (1,5,2,3,4) in the effective final ordering, even though each individual pair is technically properly sorted.

**Comment by adrianlopezroche** [comment]
Thanks.

**Comment by adrianlopezroche** [comment]
Ate you sure sorting doesn't work like it's supposed to? A quick glance at
registerpair shows it sorts the whole dupe chain, by inserting each new
match at the proper spot along the linked list.

**Comment by jbruchon** [comment]
You would think so on first glance, but I have been able to trigger incorrect sorting of the final match lists before, particularly with large sets of many small files. In any case, `registerpair()` should probably not be doing sorting work since it has to traverse a match list every single time to do that sorting and can blow away cache lines in the process. My opinion is that running a sort of each match set at the very end would be better, and it could be turned off completely when `-m` is requested.

**Comment by adrianlopezroche** [comment]
- Changed help text to read BY='name' instead of BY='filename'.
- I'm unable to reproduce the sorting issue, so ignoring it for now.

**Comment by Joshfindit** [comment]
Same problem here:
`brew install fdupes` got `fdupes 1.5.1`, but it did not support `--order`:

    fdupes: unrecognized option `--order=name'
    Try `fdupes --help' for more information.

So, cloned the repo and did make successfully.

The more pressing issue is something not actually stated in this issue, but more alluded to: Order doesn't work.

No matter what flags I run: `fdupes --order=name --reverse --delete ./` or `fdupes --order=name --delete ./`or `fdupes -r --order='time' --reverse ./` or `fdupes -r --order='time' --reverse ./` the order is always the same.
