### ISSUE TITLE
Feature Request: Fuzzy file name match

### ISSUE THREAD

**Issue by superdupercoder** [adrianlopezroche/fdupes#39]
Would be nice to have an option to find dups by fuzzy file name match.

When the files don't match perfectly on md5, this would provide an opportunity to (at least) view the files that "look" similar. One use case for this is music files obtained from multiple sources having similar names, but different checksum.

Any simple algorithm could be used for the fuzzy match.

**Comment by jbruchon** [comment]
That is an interesting proposition. The first step would be to expand the scope of `fdupes` to match based on factors other than the file contents. Once name matching is implemented, fuzzy matching is a natural future extension.

**Comment by adrianlopezroche** [comment]
That's a job for a different program. For fdupes, filenames are not supposed to matter at all. Two files could have the exact same name and not be duplicates, or be duplicates but have completely different names.

Thanks.
