### ISSUE TITLE
Install and run

### ISSUE THREAD

**Issue by rafaelstz** [adrianlopezroche/fdupes#41]
Add in README.md how to install and run.

**Comment by jbruchon** [comment]
`make` produces an executable `fdupes` that can be used anywhere; `make install` installs to `/usr/local` as most other programs do by default. If you're going to add these instructions, it would be more appropriate to create a file called INSTALL that contains such directions.

**Comment by adrianlopezroche** [comment]
See INSTALL for compilation and installation instructions.

**Comment by GibreelAbdullah** [comment]
Better to add in readme.
