### ISSUE TITLE
fdupes: reduce typing for preserve all during interactive

### ISSUE THREAD

**Issue by sandrotosi** [adrianlopezroche/fdupes#43]
_From @sandrotosi on December 20, 2015 14:4_

_From [matrixhasu](https://code.google.com/u/matrixhasu/) on October 08, 2009 21:57:09_

Debian bug `#383965` - http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=383965 I would like to have an option for the interactive mode to be able to
just preserve all files by pressing enter instead of typing "all" and
then pressing enter. 3 extra characters might not seem like much, but it
gets tiring when you have lots of files to review. For now, I'll use the
mouse to paste "all\n".

[1] ./home/pabs/projects/chm/samples-itolitls/-help2/TestCol.HxF
[2] ./home/pabs/patches/the_clit/clit12/z/TestCol.HxF

Set 76 of 1784, preserve files [1 - 2, all](220 bytes each):
---> Should skip to the next set after this
Set 76 of 1784, preserve files [1 - 2, all](220 bytes each):
Set 76 of 1784, preserve files [1 - 2, all](220 bytes each): all

Version: 1.40

_Original issue: http://code.google.com/p/fdupes/issues/detail?id=2_

_Copied from original issue: sandrotosi/fdupes-issues#2_

**Comment by sandrotosi** [comment]
_From [empee584](https://code.google.com/u/empee584/) on January 29, 2011 14:29:29_

Actually, pressing ENTER should be enough to skip a file set and keep all files...!

**Comment by sandrotosi** [comment]
_From [adrianlo...@gmail.com](https://code.google.com/u/104560115321823209294/) on March 03, 2011 11:31:18_

New interactive mode will make it possible to preserve all duplicates by pressing the "A" key without also having to press the "Enter" key.

**Status:** Accepted

**Comment by sandrotosi** [comment]
_From [adrianlo...@gmail.com](https://code.google.com/u/104560115321823209294/) on March 03, 2011 11:47:35_

**Status:** Started

**Comment by tenleftfingers** [comment]
Was this ever implemented? Pressing enter just repeats the prompt for me in 1.51.

**Comment by jbruchon** [comment]
No, it was not. It is possible to accidentally press enter twice since no one's a perfect typist, so if it ever did get implemented it should be an add-on option, not the default.

**Comment by tenleftfingers** [comment]
That's a good point jbruchon.

**Comment by adrianlopezroche** [comment]
Typing 'a' for 'all' in master branch, commit 88f3d2dd31fbef7e539b2523724221e8e8e5a9f0.
