### ISSUE TITLE
Sometimes fdupes report files pointing to same inode as duplicate even when -H parameter isn't used.

### ISSUE THREAD

**Issue by sandrotosi** [adrianlopezroche/fdupes#50]
_From @sandrotosi on December 20, 2015 14:5_

_From [sandro.tosi](https://code.google.com/u/sandro.tosi/) on April 27, 2012 18:54:25_

Hello,
I'm forwarding the Debian bug as reported at: http://bugs.debian.org/670631 >>>
Try runnig these commands:

mkdir 1 2 3
echo AAAAAAAAAAAAAAA > 1/A1
echo AAAAAAAAAAAAAAA > 2/A2
ln 1/A1 3/A3
echo BBBBBBBBBBBBBBB > 1/B1
echo BBBBBBBBBBBBBBB > 2/B2
ln 2/B2 3/B3
echo CCCCCCCCCCCCCCC > 1/C1
ln 1/C1 2/C2
echo CCCCCCCCCCCCCCC > 3/C3
ls -li [123]/[ABC][123]
fdupes -r 1 2 3
fdupes -r 1 3 2
fdupes -r 2 1 3
fdupes -r 2 3 1
fdupes -r 3 1 2
fdupes -r 3 2 1

When you run the fdupes commands, it should report two duplicate Ax files, two duplicate Bx files and two duplicate Cx files.
Not three files, as the third file is a link. But sometimes this isn't the case:

\# fdupes -r 1 3 2
3/A3
2/A2

1/B1
2/B2

1/C1
3/C3
2/C2

\# ls -li [123]/[ABC][123]
90180 -rw-r--r-- 2 root root 16 Apr 27 14:53 1/A1
90182 -rw-r--r-- 1 root root 16 Apr 27 14:53 1/B1
90185 -rw-r--r-- 2 root root 16 Apr 27 14:53 1/C1
90181 -rw-r--r-- 1 root root 16 Apr 27 14:53 2/A2
90184 -rw-r--r-- 2 root root 16 Apr 27 14:53 2/B2
90185 -rw-r--r-- 2 root root 16 Apr 27 14:53 2/C2
90180 -rw-r--r-- 2 root root 16 Apr 27 14:53 3/A3
90184 -rw-r--r-- 2 root root 16 Apr 27 14:53 3/B3
90186 -rw-r--r-- 1 root root 16 Apr 27 14:53 3/C3

As seen above, fdupes report "1/C1" and "2/C2" ad duplicates, even though they point to the same inode.
\<<<

Regards,
Sandro

_Original issue: http://code.google.com/p/fdupes/issues/detail?id=24_

_Copied from original issue: sandrotosi/fdupes-issues#9_

**Comment by adrianlopezroche** [comment]
Fixed.

**Comment by sandrotosi** [comment]
FTR, this is closed via https://github.com/adrianlopezroche/fdupes/commit/79e41f1477cdde3da58bfe5d76927f4e62fca518

**Comment by adrianlopezroche** [comment]
Also needed is https://github.com/adrianlopezroche/fdupes/commit/4932aa55a2ecdbe2a5c874a220605f9215cca20a
