### ISSUE TITLE
Free memory after a duplicate was handled

### ISSUE THREAD

**Issue by berlincount** [adrianlopezroche/fdupes#59]
Apparently, memory for a dupe isn't freed after it was handled.

This means the system stays under memory/swap pressure even after most of a (very large) set of files was handled.

Memory should be freed earlier.

**Comment by jbruchon** [comment]
The data structure used to store the file list is a tree, but the duplicate lists are linked lists that traverse the tree in an unpredictable manner. If "handled" duplicates get freed, the tree linkages will break and the program will crash. There is not any practical way to free memory earlier without greatly increasing the complexity of the software to little benefit; profiling with Massif shows that memory usage never even hits the 100MB mark with tens of thousands of files in the tree.

**Comment by adrianlopezroche** [comment]
Agreeing with jbruchon. Closing.
