### ISSUE TITLE
sha256 instead of md5

### ISSUE THREAD

**Issue by jaromil** [adrianlopezroche/fdupes#61]
Hello and thanks for fdupes,

I am concerned that MD5 can be weak under some circumstances and weak to attacks (one may forge a file colliding md5 to force the deletion of something from an archive). For this reason I'm interested in enhancing fdupes with a SHA256 detection mechanism in place of MD5, which may be provided by a standalone implementation or by the OpenSSL shared library one.

Do you have any intention to merge such a pull request?

**Comment by jbruchon** [comment]
For data safety concerns, the hash doesn't matter. Even if the hash collision rate was 100%, no non-duplicate files would be matched as duplicates. After a duplicate match is confirmed by hash comparisons, the program compares each byte in each file to guarantee that the match is 100% accurate. "Upgrading" to a slower hash algorithm will slow the program down to no benefit. If anything, [the hash algorithm choice should go the other way](https://github.com/jbruchon/jodyhash) and allow for a few rare collisions in exchange for [a big speed boost.](https://github.com/jbruchon/jdupes/commit/f99ae1476bbc67733f8618ac6a301db159d2f18d)

**Comment by jaromil** [comment]
I clearly see your point now. Pardon my ignorance on the algorithm and thanks for your explanation.

**Comment by jbruchon** [comment]
Glad I could help!
