### ISSUE TITLE
delete files progressively, not just at the end of the scan

### ISSUE THREAD

**Issue by sandrotosi** [adrianlopezroche/fdupes#63]
fdupes sometimes take a long time to run, in particular if you have a lot of files and their size is big, and if you interrupt fdupes while it still parses the files list for dupes, you basically lost all the processing done so far.

it would be ideal to have an option to delete dupes as fdupes find them, so that every time you ctrl+c at least you've remove a part of the duplicates

**Comment by jbruchon** [comment]
`fdupes` is welcome to copy my implementation of this from https://github.com/jbruchon/jdupes/commit/9f7dfef781162762aa46becb7c531e88758095f4

**Comment by adrianlopezroche** [comment]
OK. I'm going to work on this, but using a different approach than jbruchon
so please wait for my version.

**Comment by adrianlopezroche** [comment]
Implemented in https://github.com/adrianlopezroche/fdupes/commit/1b74368b9b4c2dadb94a4774b5cb1fc15dba5a4d

**Comment by sandrotosi** [comment]
thanks @adrianlopezroche !! btw, are you planning a new release? there was quite some development since 1.51

**Comment by adrianlopezroche** [comment]
I guess I should make a new release. I was sort of waiting to finish the ncurses interface, but I should probably just release what I have as 1.6 or something.

**Comment by adrianlopezroche** [comment]
I've gone ahead and released master branch as 1.6.0.

**Comment by sandrotosi** [comment]
thanks @adrianlopezroche !! just a small question: the previous release was 1.51 while now with 1.6.0/1.6.1 it means the version is actually lower than it was before (as 6 sorts numerically before 51). is this the new format of versions you're going to release with from now on? this causes a small issue with the debian versioning, but it can be addressed, i just want to be sure it was not just an overlook and it's something you considered

**Comment by adrianlopezroche** [comment]
Yes, the change in the versioning format is intentional. The second digit
after the decimal point in the old scheme served the same purpose as the
"patch" digit in the new scheme while allowing the minor version number to
grow beyond 9.

Hope it's not too much trouble, but I intend to use the x.y.z format from
now on.

**Comment by adrianlopezroche** [comment]
Yes, the change in the versioning scheme is intentional. The second decimal digit of the old format served the same purpose as the "patch" digit in the new format, but the new one allows the minor version number to grow beyond 9.

Hope it's not too much trouble, but I do intend to use the x.y.z format from now on.

**Comment by sandrotosi** [comment]
nope that's ok, i can deal with it, it just wanted to make sure that's all under control - thanks for the quick reply!

**Comment by sergiomb2** [comment]
> Hope it's not too much trouble, but I do intend to use the x.y.z format from now on.

it is trouble , maths is maths  , the release version can't be 1.6 since 6 is not bigger than 50 . , you may use 1.60.0 for example

**Comment by adrianlopezroche** [comment]
Is there a distro you're maintaining where this is a problem? The old X.YZ
scheme was always meant to represent major, minor, patch, which the new one
does explicitly.

I do understand it changes the sort order, but I'd like to know whether
it's causing particular problems.
