### ISSUE TITLE
release 1.51 is bigger  than 1.6.0 

### ISSUE THREAD

**Issue by sergiomb2** [adrianlopezroche/fdupes#65]
Our release-monitoring is right [1] from 1.51 you can't change to 1.6 , or form 1.40 to 1.6.0 , maybe release 1.60.0 ? 

[1] 
https://release-monitoring.org/project/786/

**Comment by sandrotosi** [comment]
this has already been discussed: https://github.com/adrianlopezroche/fdupes/issues/63#issuecomment-243094218

**Comment by sergiomb2** [comment]
I mean the release , the release version  can't be 1.6 since 6 is not bigger than 50 .

**Comment by sandrotosi** [comment]
well, it can, and it's not like the first time it happened in the sw release history. Adrian already explained (in the comment i linked before, the X.Y.Z format is the new schema and X.YY will not be used anymore) just fix your monitoring tool to accommodate it

**Comment by sergiomb2** [comment]
Well , will give work to all distros etc etc

**Comment by sandrotosi** [comment]
a new release already gives work to all distros... you can nitpick on the version or accept that a new release is always a great thing (in particular for fdupes) and just deal with the situation and move on

**Comment by sergiomb2** [comment]
https://rpmfind.net/linux/rpm2html/search.php?query=fdupes no much distros, but ok , or we just change now , or is too late .

Thanks for your time , anyway I think we should educate upstream :smiley:

**Comment by jbruchon** [comment]
Making 1.51 sort lower than 1.6.0 is certainly a pain though. What happens to the sort of choice when it reaches 1.10.0? Will it read as 1.1.0.0 and sort 1.10.0 below 1.6.0? *shrug* I would have just opted for a 2.0 release to avoid problems and whatever big feature was planned to trigger a 2.0 release could be a 3.0 release.

Anyway, it's done now, so there is no sense in complaining about it, and as long as it doesn't become 1.10* anywhere along the way, an exception is easy enough to implement.

**Comment by adrianlopezroche** [comment]
Looking at the list of packages at release-monitoring where this has
happened, perhaps the problem lies with the service's assumptions about
versioning?

[1] https://release-monitoring.org/projects/updates/odd

**Comment by adrianlopezroche** [comment]
It would be 1.10.0 (as is the usual practice when using this format) which
in the old scheme would have been 1.100. I'll probably end up releasing the
upcoming ncurses-capable version (release date undetermined) as 2.0.0.

**Comment by sergiomb2** [comment]
We can (like Debian did) use epoch , so we bump epoch  and 0:1.51 < 1:1.6 , and I have to ask to admin on release monitoring to clear history of fdupes and another minor problems that other distros can have like fail to detect a new version.
Do 2.0 for me is a good alternative , change numeration not always means big changes in code, you got example of kernel . 

Now I'd like to know if you going to fix this issue or not ? to processed , no rush .
Thanks.

**Comment by sergiomb2** [comment]
I give up
