### ISSUE TITLE
Feature request: delete file then make symlink or hardlink to reference file

### ISSUE THREAD

**Issue by icve** [adrianlopezroche/fdupes#66]
I would love an option to delete file then make symlink to reference file.
For example, 
/some/dir/file1
/some/dir/file2 

`fdupes -d --symlinkfirst /some/dir`

/some/dir/file1
/some/dir/file2 > /some/dir/file1

And option to move all first duplicated files to a directory then point symlinks to the files in the directory,
For example:
/some/dir/file1
/some/dir/file2
`fdupes --refdir=/some/ref_dir /some/dir`
/some/ref_dir/file1
/some/dir/file1 > /some/ref_dir/file1
/some/dir/file2 > /some/ref_dir/file1

**Comment by jbruchon** [comment]
Tasks like this are usually better suited to shell scripts that operate on the default output of fdupes. Feed the output to a while loop that uses the blank line between sets to reset its behavior. You can do any sort of arbitrary operations on file sets using a shell script while loop. There are a lot of possible operation variants like yours and it is somewhat impractical for them all to get added as options. If you would like an example snippet of code, let me know and I'll write one here.

**Comment by icve** [comment]
Thanks, I would love to have see how it can be done in script.

**Comment by jbruchon** [comment]
An example of symlinking everything in a set to the first file in the set:
```shell
fdupes /some/dir1 /some/dir2 | while read LINE
  do
  # Initialize (can't do this before the loop because this 'while' is running in a subshell)
 test -z "$X" && X=0
  # At start of new set, change link source file
  test "$X" = "0" && SRC="$LINE" && continue
  X=1
  # At each empty line, start a new set
  test -z "$X" && X=0 && continue
  # If nothing else returned to the start of the loop by now, make a symlink
  ln -sf "$SRC" "$LINE"
done
```
