### ISSUE TITLE
Feature request: implement reverse order when sorting on filename too

### ISSUE THREAD

**Issue by onstrees** [adrianlopezroche/fdupes#73]
Being a linux newbee, fdupes is the first program I compile, and I did so specifically to have the new sorting option -o --order=BY. My use case is that I want to delete all files in one folder that are duplicates of a file in another folder, and not delete some of them from the first folder, and delete others from the second folder.

I first used Ubuntu software center to install fdupes, version 1.5.1, and it presented the duplicates not consistently ordered by path, but (as I now know) by time. This required me to be very concentrated to press the right key 1 or 2 for each set of duplicates.

With version 1.6.1, now freshly compiled on my pc, I can relay on always having to press the same key to delete files in always the same folder. But I still have to press the keys many times.

If I could influence the sort order to be reversed, I could get all duplicates in the folder I want to delete from, to be number 1 (because sorting on file name is in fact sorting on path name first), and so I could use the -N --noprompt option.

I used to program in C long time ago, and the reverse order could be as simple as returning -strcmp(...)

**Comment by FabioPedretti** [comment]
Fixed by #102?

**Comment by adrianlopezroche** [comment]
Yes, fixed.
