### ISSUE TITLE
Cache hashes (based on path and modification time)

### ISSUE THREAD

**Issue by Harvie** [adrianlopezroche/fdupes#80]
Maybe it would be usefull to have some kind of hash cache in `~/.cache/fdupes` that would allow to SAFELY reuse hashes if file modification time was not changed. Both `rsync` and `make` are doing this all the time. (they do not cache, but they compare files based on modification time)

**Comment by hellyberry** [comment]
You cannot safely detect modification by looking at the modification time. This is easily reset/modified ("touched") in filesystem.

**Comment by hellyberry** [comment]
So such a "feature" is contrary to fdupes aim - detecting securely and fast any real duplicates.

**Comment by Harvie** [comment]
It's not really going to be problem. Because typical "touch" emulates file modification. So that would invalidate any cached hashes. On the other hand to really fool the fdupes to think that file has not changed, while it has you'd have to modify it and then touch it with parameter setting file modification time to the past exactly to the time that it had before and it had cached. If the file will have modification date before cached date (that may happen when there's problem with system clock or due to NTP failure) it can be perceived as invalid and fdupes can proceed as usual.

Doing something like this can be safely assumed stupid and it's something that nobody who cares about his data will do. Because it may lead to data loss when using rsync and other backup tools, which is widely used far more often than fdupes. Also rsync is still perceived as popular and secure way to sync data even while using this strategy.


Anyway... This can be implemented as optional feature activated by some commandline flag. And time will show us how popular it gets. I am using fdupes on storage where people don't have direct access to filesystem, so nobody can mess with timestamps, screwing around and touching files into the past, so this makes big sense for my use case.

**Comment by hellyberry** [comment]
Such a "feature" is contrary to fdupes aim - detecting securely and fast any real duplicates.

**Comment by roycewilliams** [comment]
Concur with @Harvie. If it's an optional flag, then the syadmin gets to choose the tradeoff. When it's a system that I maintain privately, I would love to be able to cache the results, especially for large files, and tell fdupes "it's OK, assume no one is monkeying with timestamps" or perhaps also "check the first and last X bytes as a crosscheck to see if the cached checksum needs to be refreshed."

My workflow when using fdupes would be massively improved if I could run it much more quickly (on subsequent runs). It would enable me to run it much more often.

**Comment by adrianlopezroche** [comment]
I've finally implemented a version of this using SQLite. The code looks at file creation time, modification time, size, and inode to determine whether a file's contents are likely to have changed. If none of these values have changed the code assumes the hash remains the same, which could lead to missed duplicates (the old hash doesn't match any files but the new one would) or false matches (the old hash matches but the new one wouldn't). Neither condition should result in lost data, however, in the latter case because fdupes will check for an actual match by doing a byte-for-byte comparison before reporting a match.

Solved by ab5ef95e2b2633d0ca1a5ae0b8ac41abde160100.

**Comment by roycewilliams** [comment]
That sounds like a great approach!

**Comment by adrianlopezroche** [comment]
Correction: the code doesn't look at file creation time but at the node change time (ctime). The advantage of this is that ctime, unlike modification time, is very hard to fake. You'd have to either change the system clock and time your file changes just right
