### ISSUE TITLE
[FR] Allow to specify min/max file size

### ISSUE THREAD

**Issue by DEVoytas** [adrianlopezroche/fdupes#83]
At the moment `fdupes` allows to exclude zero-length files from consideration with the use of option `-n` or `--noempty`. This can be improved by allowing to specify arbitrary file size, and maybe even interval (i.e. specify minimum and maximum size).

**Comment by feluxe** [comment]
This would be really useful. Running `fdupes` on large directories can take a very long time. I'm in a situation where I only need to dedupe files `>100MB`. Having an `min-size` option for that would speed up the process a lot, I guess.

**Comment by adrianlopezroche** [comment]
Fixed in fda883c44de67b94bda697690407845b9db99f15.
