### ISSUE TITLE
Allow option to choose 'none' for fdupes -d

### ISSUE THREAD

**Issue by tenleftfingers** [adrianlopezroche/fdupes#97]
I'm given the option to choose a range for deletion (eg [1 - 4]) or 'all'. But I cannot choose 'none' in instances where I need to keep the duplicates.

I've tried typing 'none', '0', 'no' and pressing return with no text typed. I am continuously prompted to make a choice for deletion and cannot continue to the next sets.

**Comment by jbruchon** [comment]
The deletion is asking you which to KEEP, not which to DELETE. You want to keep "a" for all. That being said, I added the "n" option to [jdupes](https://github.com/jbruchon) some time ago if you want the "keep none" feature.

**Comment by tenleftfingers** [comment]
Thanks Jody. I was following an online article which describes it as a choice of which to delete https://www.tecmint.com/fdupes-find-and-delete-duplicate-files-in-linux/comment-page-1/#comment-966725 <https://www.tecmint.com/fdupes-find-and-delete-duplicate-files-in-linux/comment-page-1/#comment-966725>

But it’s clear from reading the terminal that the choice is of which to “preserve”.
