### ISSUE TITLE
Feature request: automatic de-duplication

### ISSUE THREAD

**Issue by tenleftfingers** [adrianlopezroche/fdupes#98]
I'm currently in a scenario where I have almost 10k sets to compare. I would like to just tell fdupes to choose option 1 for everything. I'm happy to save time and risk some mistakes with this data, which is useful but not vital.

**Comment by jbruchon** [comment]
You're looking for the `-N` option which allows `-d` to preserve the first file in each set only, deleting all others.

**Comment by tenleftfingers** [comment]
Thanks again jbruchon.

**Comment by adrianlopezroche** [comment]
fdupes --delete --noprompt
